[project]
name = "workshop-helper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "argparse>=1.4.0",
    "clipboard>=0.0.4",
    "datetime>=5.5",
    "pyautogui>=0.9.54",
]

[dependency-groups]
dev = [
    "black>=26.5.1",
]
